In [3]:
import numpy as np
from tqdm import tqdm

# Load and PreProcess Data

In [4]:
with open ("data/genes.txt", "r") as file:
    genes = file.readlines()

In [5]:
expr = np.loadtxt("data/model.txt")

In [6]:
geneDic = {}
for i in tqdm(range(len(genes))):
    geneDic[genes[i][:-1]] = i

100%|███████████████████████████████████████████████████████████████████████████████| 17/17 [00:00<00:00, 17017.46it/s]


# Problem 1

In [7]:
# order is NCAPG FOS FOXA1 ESR1
order = ['NCAPG', 'FOS', 'FOXA1', 'ESR1']

In [8]:
orderIndex = []
for i in range(len(order)):
    orderIndex.append(geneDic[order[i]])

In [9]:
orderIndex

[3, 6, 5, 8]

In [204]:
n_samples = 1000000
samples = np.zeros((n_samples, 4))

In [208]:
for i in range(4):
    if i != 0:
        prev_mean = np.mean(samples[:,i-1])
    for j in range(n_samples):
        if i == 0:
            samples[j,i] = np.random.normal(loc = expr[orderIndex[i], 17], scale = np.sqrt(expr[orderIndex[i], 18]))
        else:
            samples[j,i] = np.random.normal(loc = expr[orderIndex[i], 17]+expr[orderIndex[i], orderIndex[i-1]]*prev_mean, scale = np.sqrt(expr[orderIndex[i], 18]))

In [200]:
mean, variance = np.mean(samples[:,3]), np.var(samples[:,3])

In [201]:
print(mean)
print(variance)

-190.7883495046886
0.1335864076621784


# Problem 2

In [189]:
def LinearRegression(X_train, y_train):
#     mean centering the data
    X = X_train-np.mean(X_train,axis = 0)
    y = y_train-np.mean(y_train,axis = 0)

    # based on the closed form expression, compute the result directly
    theta = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)

    return theta

In [217]:
def LR(X_train, y_train, beta):
    X = X_train
    y = y_train
    theta = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y-beta)

    return theta

In [218]:
beta =[]
for i in range(4):
    y_train = samples[:,i].reshape(-1,1)
    if i == 0:
        X_train = samples[:,i].reshape(-1,1)
    else:
        X_train = samples[:,i-1].reshape(-1,1)
    beta_i = LR(X_train, y_train, expr[orderIndex[i], 17])
    beta.append(beta_i)

In [219]:
beta

[array([[0.00348752]]),
 array([[2.69569476]]),
 array([[1.89967761]]),
 array([[-1.79973344]])]